This notebook explores the robustness of the eight measures at the patent and industrial level.

The eight measures are listed below

# At the patent value

Binary main class D-D

Binary sub class D-D

Continuous main class D-D

Continuous sub class D-D

Binary main class D-U

Binary sub class D-U

Continuous main class D-U

Continuous sub class D-U

# At the industry level
Binary main class (%) D-D

Binary sub class (%) D-D

Continuous main class (mean of max scores) D-D

Continuous sub class (mean of max scores) D-D

Binary main class (%) D-U

Binary sub class (%) D-U

Continuous main class (mean of max scores) D-U

Continuous sub class (mean of max scores) D-U

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import design_class_dictionary

%matplotlib inline

In [2]:
#reading in data
# master = pd.read_csv('data/master_503107.csv')
master = pd.read_csv('data/master_437678.csv.csv')
master.head()

,patent_number,grant_year,app_year,num_inventors,us_inventor,cite_foreign_patent,is_missing,num_design_cited,num_utility_cited,non-pat_refs,num_figures,num_assignees,missing_data,family_size,country_transformed,priority_date,origin
0,D257752,1981,1980,1,1,0,1,1,2,1,6,1,0,1,US,1980.0,0
1,D257924,1981,1980,1,1,0,1,1,2,1,6,1,0,1,US,1980.0,0
2,D258382,1981,1980,2,1,0,1,2,1,0,5,1,0,1,US,1980.0,0
3,D258383,1981,1980,2,1,0,1,2,1,0,5,1,0,1,US,1980.0,0
4,D258678,1981,1980,2,1,0,1,2,1,0,5,1,0,1,US,1980.0,0

In [3]:
# binary_main_d = pd.read_csv('data/d2d_main_binary.csv')
# binary_sub_d = pd.read_csv('data/d2d_sub_binary.csv')
# cont_main_d = pd.read_csv('data/d2d_main_cont.csv')
# cont_sub_d = pd.read_csv('data/d2d_sub_cont.csv')

# binary_main_u = pd.read_csv('data/d2u_main_binary.csv')
# binary_sub_u = pd.read_csv('data/d2u_sub_binary.csv')
# cont_main_u = pd.read_csv('data/d2u_main_cont.csv')
# cont_sub_u = pd.read_csv('data/d2u_sub_cont.csv')

In [4]:
binary_main_d = pd.read_csv('data/d2d_main_binary_drops.csv')
binary_sub_d = pd.read_csv('data/d2d_sub_binary_drops.csv')
cont_main_d = pd.read_csv('data/d2d_main_cont_drops.csv')
cont_sub_d = pd.read_csv('data/d2d_sub_cont_drops.csv')

binary_main_u = pd.read_csv('data/d2u_main_binary_drops.csv')
binary_sub_u = pd.read_csv('data/d2u_sub_binary_drops.csv')
cont_main_u = pd.read_csv('data/d2u_main_cont_drops.csv')
cont_sub_u = pd.read_csv('data/d2u_sub_cont_drops.csv')

In [5]:
binary_main_d.head()

  patent_number  is novel  novelty count
0       D258990         1              2
1       D259247         1              2
2       D259248         1              2
3       D259249         1              2
4       D259250         1              2

In [6]:
cont_main_d.head()

  patent_number  max_novelty
0       D258990    -0.167627
1       D259247     0.015794
2       D259248     0.015794
3       D259249     0.015794
4       D259250     0.015794

# Explore at the patent level first

In [7]:
def add_column(df, column, column_name):
    df = pd.merge(df, column, on='patent_number', how='left')
    return df

In [8]:
# Merge the binary measures into master dataframe

master = pd.merge(master, binary_main_d, on='patent_number', how='left')
master = master.rename(index=str, columns={'is novel':'is novel binary main: D-D',\
                                  'novelty count':'novelty count binary main: D-D'})

master = pd.merge(master, binary_sub_d, on='patent_number', how='left' )
master = master.rename(index=str, columns={'is novel':'is novel binary sub: D-D',\
                                          'novelty count':'novelty count binary sub: D-D'})

master = pd.merge(master, binary_sub_u, on='patent_number', how='left')
master = master.rename(index=str, columns={'is novel':'is novel binary main: D-U',\
                                          'novelty count':'novelty count binary main: D-U'})

master = pd.merge(master, binary_sub_u, on='patent_number', how='left')
master = master.rename(index=str, columns={'is novel':'is novel binary sub: D-U',\
                                          'novelty count':'novelty count binary sub: D-U'})

In [9]:
# merge the continuous into master dataframe

master = pd.merge(master, cont_main_d, on='patent_number', how='left')
master = master.rename(index=str, columns={'max_novelty':'max novelty main: D-D'})

master = pd.merge(master, cont_sub_d, on='patent_number', how='left' )
master = master.rename(index=str, columns={'max_novelty':'max novelty sub: D-D'})

master = pd.merge(master, cont_sub_u, on='patent_number', how='left')
master = master.rename(index=str, columns={'max_novelty':'max novelty main: D-U'})

master = pd.merge(master, cont_sub_u, on='patent_number', how='left')
master = master.rename(index=str, columns={'max_novelty':'max novelty sub: D-U'})

In [10]:
#select the columns with just the measures
columns = master[['is novel binary main: D-D','is novel binary sub: D-D',\
        'is novel binary main: D-U','is novel binary sub: D-U','max novelty main: D-D',\
        'max novelty sub: D-D','max novelty main: D-U','max novelty sub: D-U']]
columns.head()

,is novel binary main: D-D,is novel binary sub: D-D,is novel binary main: D-U,is novel binary sub: D-U,max novelty main: D-D,max novelty sub: D-D,max novelty main: D-U,max novelty sub: D-U
0,NaN,NaN,1.0,1.0,NaN,NaN,-4.951017,-4.951017
1,NaN,NaN,1.0,1.0,NaN,NaN,-5.724207,-5.724207
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Examing the correlation of design citing design measures for binary and continous measures, at mainclass and subclass level

In [11]:
matrix = columns[['is novel binary main: D-D','is novel binary sub: D-D','max novelty main: D-D',\
                  'max novelty sub: D-D']].dropna()

# count the number of observations
matrix.shape

(180687, 4)

There are 475,267 non-null observations for these measures

In [12]:
#correlation matrix
matrix.corr().round(3)

,is novel binary main: D-D,is novel binary sub: D-D,max novelty main: D-D,max novelty sub: D-D
is novel binary main: D-D,1.000,0.069,-0.015,-0.069
is novel binary sub: D-D,0.069,1.000,0.256,0.105
max novelty main: D-D,-0.015,0.256,1.000,0.135
max novelty sub: D-D,-0.069,0.105,0.135,1.000

Examing the correlation of design citing utility measures for binary and continous measures, at mainclass and subclass level

In [13]:
matrix = columns[['is novel binary main: D-U','is novel binary sub: D-U','max novelty main: D-U',\
                  'max novelty sub: D-U']].dropna()

#count the number of observations
matrix.shape

(265176, 4)

There are 308,725 non-null observations for these measures

In [14]:
matrix.corr().round(3)

,is novel binary main: D-U,is novel binary sub: D-U,max novelty main: D-U,max novelty sub: D-U
is novel binary main: D-U,1.000,1.000,0.171,0.171
is novel binary sub: D-U,1.000,1.000,0.171,0.171
max novelty main: D-U,0.171,0.171,1.000,1.000
max novelty sub: D-U,0.171,0.171,1.000,1.000

Comparing all 8 measures

In [15]:
matrix = columns.dropna()

#count the number of observations
matrix.shape

(120608, 8)

There are 280,885 observations

In [16]:
matrix.corr().round(3)

,is novel binary main: D-D,is novel binary sub: D-D,is novel binary main: D-U,is novel binary sub: D-U,max novelty main: D-D,max novelty sub: D-D,max novelty main: D-U,max novelty sub: D-U
is novel binary main: D-D,1.000,0.051,0.030,0.030,-0.009,-0.051,-0.033,-0.033
is novel binary sub: D-D,0.051,1.000,0.317,0.317,0.259,0.126,0.037,0.037
is novel binary main: D-U,0.030,0.317,1.000,1.000,0.081,0.025,0.177,0.177
is novel binary sub: D-U,0.030,0.317,1.000,1.000,0.081,0.025,0.177,0.177
max novelty main: D-D,-0.009,0.259,0.081,0.081,1.000,0.155,0.024,0.024
max novelty sub: D-D,-0.051,0.126,0.025,0.025,0.155,1.000,0.547,0.547
max novelty main: D-U,-0.033,0.037,0.177,0.177,0.024,0.547,1.000,1.000
max novelty sub: D-U,-0.033,0.037,0.177,0.177,0.024,0.547,1.000,1.000

In [17]:
#save the table
# matrix.to_csv('data/design_cite_design_design_cite_utility_corr.csv')
matrix.to_csv('data/design_cite_design_design_cite_utility_corr_drops.csv')

# Examing at the industrial level

We need to attribute each patent to an industry. I have taken the first listed class, known as primary class, of a patent as the industry

In [18]:
# read in the data file from PatStat that lists all patent classes and their sequences
pat_class = pd.read_csv('data/uspc_current.tsv', delimiter='\t', usecols=['patent_id','mainclass_id','sequence'],\
                        dtype={'patent_id':str})
pat_class.head()

  patent_id mainclass_id  sequence
0   3930271            2         0
1   3930271            2         1
2   3930271            2         2
3   3930271          473         3
4   3930272            5         0

In [19]:
#select first listed class
pat_class_first = pat_class.loc[pat_class.sequence == 0]
master = pd.merge(master, pat_class_first, left_on='patent_number',right_on='patent_id', how='left')

In [20]:
master.head()

,patent_number,grant_year,app_year,num_inventors,us_inventor,cite_foreign_patent,is_missing,num_design_cited,num_utility_cited,non-pat_refs,...,novelty count binary main: D-U,is novel binary sub: D-U,novelty count binary sub: D-U,max novelty main: D-D,max novelty sub: D-D,max novelty main: D-U,max novelty sub: D-U,patent_id,mainclass_id,sequence
0,D257752,1981,1980,1,1,0,1,1,2,1,...,3.0,1.0,3.0,NaN,NaN,-4.951017,-4.951017,D257752,D19,0.0
1,D257924,1981,1980,1,1,0,1,1,2,1,...,3.0,1.0,3.0,NaN,NaN,-5.724207,-5.724207,D257924,D06,0.0
2,D258382,1981,1980,2,1,0,1,2,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D258382,D23,0.0
3,D258383,1981,1980,2,1,0,1,2,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D258383,D23,0.0
4,D258678,1981,1980,2,1,0,1,2,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D258678,D23,0.0

In [21]:
#Checking the primary classes of these patents for uniformity or unexpected values
master.mainclass_id.unique()

array(['D19', 'D06', 'D23', 'D25', 'D09', 'D24', 'D11', 'D12', 'D21',
       'D08', 'D10', 'D07', 'D22', 'D02', 'D13', 'D34', 'D17', 'D18',
       'D30', 'D14', 'D28', 'D03', 'D27', 'D15', 'D26', 'D32', 'D20',
       'D99', 'D16', 'D04', 'D01', 'D29', 'D05', 'D8', 'D9', 'D6', 'D7',
       '1', '70', '24', nan], dtype=object)

In [22]:
# harmonize the class names. ie D8 -> D08
master['mainclass_id'] = master['mainclass_id'].replace(design_class_dictionary.class_dictionary)

In [23]:
# Dropping the null value, it's useless
master = master.dropna(subset=['mainclass_id'])

#Selecting only valid primary design classes
master = master.loc[master.mainclass_id.str.contains('D')]

In [24]:
#selecting the columns of the measures and the primary classes
columns = master[['is novel binary main: D-D','is novel binary sub: D-D',\
        'is novel binary main: D-U','is novel binary sub: D-U','max novelty main: D-D',\
        'max novelty sub: D-D','max novelty main: D-U','max novelty sub: D-U', 'mainclass_id']]
columns.head()

,is novel binary main: D-D,is novel binary sub: D-D,is novel binary main: D-U,is novel binary sub: D-U,max novelty main: D-D,max novelty sub: D-D,max novelty main: D-U,max novelty sub: D-U,mainclass_id
0,NaN,NaN,1.0,1.0,NaN,NaN,-4.951017,-4.951017,D19
1,NaN,NaN,1.0,1.0,NaN,NaN,-5.724207,-5.724207,D06
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D23
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D23
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D23

In [25]:
'''
Creating the table of measures consolidated at the industry level
The mean is taken for the max novelty and binary measures
Since the binary measure only takes on the value of 1 or 0, the mean is equivalent
calculating the percentage of positive occurences
'''
table = columns.groupby('mainclass_id').mean().round(3).reset_index()
table['class name'] = table['mainclass_id'].map(design_class_dictionary.class_labels)
table

,mainclass_id,is novel binary main: D-D,is novel binary sub: D-D,is novel binary main: D-U,is novel binary sub: D-U,max novelty main: D-D,max novelty sub: D-D,max novelty main: D-U,max novelty sub: D-U,class name
0,D01,0.010,0.655,0.840,0.840,1.187,-3.179,-4.865,-4.865,Edible Products
1,D02,0.007,0.309,0.597,0.597,0.821,-2.647,-4.463,-4.463,Apparel and Haberdashery
2,D03,0.006,0.497,0.786,0.786,1.440,-2.494,-3.939,-3.939,"Travel Goods, Personal Belongings, and Storage..."
3,D04,0.011,0.345,0.681,0.681,0.488,-3.559,-4.330,-4.330,Brushware
4,D05,0.018,0.530,0.822,0.822,0.968,-3.240,-3.933,-3.933,Textile or Paper Yard Goods; Sheet Material
5,D06,0.008,0.414,0.751,0.751,1.304,-3.093,-4.779,-4.779,Furnishings
6,D07,0.005,0.453,0.714,0.714,1.207,-2.637,-4.236,-4.236,Equipment for Preparing or Serving Food or Dri...
7,D08,0.004,0.357,0.718,0.718,1.287,-3.181,-4.576,-4.576,Tools and Hardware
8,D09,0.006,0.517,0.776,0.776,1.020,-0.804,-3.090,-3.090,Packages and Containers for Goods
9,D10,0.007,0.339,0.745,0.745,1.328,-3.152,-5.308,-5.308,"Measuring, Testing or Signaling Instruments"
10,D11,0.008,0.507,0.711,0.711,1.295,-3.333,-5.383,-5.383,"Jewelry, Symbolic Insignia, and Ornaments"
11,D12,0.005,0.299,0.692,0.692,1.211,-4.795,-5.857,-5.857,Transportation
12,D13,0.002,0.283,0.640,0.640,0.959,-2.878,-4.285,-4.285,"Equipment for Production, Distribution, or Tra..."
13,D14,0.004,0.317,0.623,0.623,0.690,-2.280,-3.817,-3.817,"Recording, Communication, or Information Retri..."
14,D15,0.007,0.330,0.762,0.762,1.003,-4.565,-5.378,-5.378,Machines Not Elsewhere Specified
15,D16,0.007,0.272,0.540,0.540,1.108,-3.615,-4.991,-4.991,Photography and Optical Equipment
16,D17,0.033,0.314,0.545,0.545,1.100,-5.068,-6.313,-6.313,Musical Instruments
17,D18,0.010,0.304,0.607,0.607,0.960,-3.736,-5.649,-5.649,Printing and Office Machinery
18,D19,0.010,0.563,0.789,0.789,1.453,-1.947,-4.292,-4.292,Office Supplies; Artists' and Teachers' Materials
19,D20,0.005,0.528,0.848,0.848,1.493,-2.899,-4.346,-4.346,Sales and Advertising Equipment
20,D21,0.006,0.480,0.695,0.695,1.347,-4.839,-5.655,-5.655,"Games, Toys and Sports Goods"
21,D22,0.008,0.314,0.573,0.573,1.058,-5.124,-5.960,-5.960,"Arms, Pyrotechnics, Hunting and Fishing Equipment"
22,D23,0.007,0.291,0.755,0.755,1.061,-4.051,-5.046,-5.046,"Environmental Heating and Cooling, Fluid Handl..."
23,D24,0.013,0.380,0.675,0.675,1.270,-3.286,-4.439,-4.439,Medical and Laboratory Equipment
24,D25,0.008,0.356,0.743,0.743,1.264,-4.804,-5.022,-5.022,Building Units and Construction Elements
25,D26,0.002,0.349,0.732,0.732,1.065,-3.192,-4.045,-4.045,Lighting
26,D27,0.014,0.562,0.785,0.785,1.271,-4.441,-5.950,-5.950,Tobacco and Smokers' Supplies
27,D28,0.009,0.416,0.653,0.653,1.222,-3.865,-5.450,-5.450,Cosmetic Products and Toilet Articles
28,D29,0.011,0.393,0.668,0.668,0.529,-4.666,-4.922,-4.922,"Equipment for Safety, Protection and Rescue"
29,D30,0.005,0.576,0.710,0.710,1.366,-2.955,-4.888,-4.888,Animal Husbandry
30,D32,0.005,0.338,0.675,0.675,1.153,-4.231,-4.921,-4.921,"Washing, Cleaning or Drying Machines"
31,D34,0.006,0.369,0.731,0.731,1.252,-3.421,-4.374,-4.374,Material or Article Handling Equipment
32,D99,0.013,0.591,0.746,0.746,1.286,-3.520,-5.404,-5.404,Miscellaneous

In [26]:
#save this table
# table.to_csv('data/table.csv')
table.to_csv('data/table_drops.csv')

In [27]:
#correlation of measures at the industry level
table.corr().round(3)

,is novel binary main: D-D,is novel binary sub: D-D,is novel binary main: D-U,is novel binary sub: D-U,max novelty main: D-D,max novelty sub: D-D,max novelty main: D-U,max novelty sub: D-U
is novel binary main: D-D,1.000,0.111,-0.167,-0.167,-0.090,-0.334,-0.395,-0.395
is novel binary sub: D-D,0.111,1.000,0.686,0.686,0.450,0.339,0.159,0.159
is novel binary main: D-U,-0.167,0.686,1.000,1.000,0.423,0.322,0.347,0.347
is novel binary sub: D-U,-0.167,0.686,1.000,1.000,0.423,0.322,0.347,0.347
max novelty main: D-D,-0.090,0.450,0.423,0.423,1.000,0.080,-0.162,-0.162
max novelty sub: D-D,-0.334,0.339,0.322,0.322,0.080,1.000,0.825,0.825
max novelty main: D-U,-0.395,0.159,0.347,0.347,-0.162,0.825,1.000,1.000
max novelty sub: D-U,-0.395,0.159,0.347,0.347,-0.162,0.825,1.000,1.000

In [28]:
#Save the correlation table
# table.corr().round(3).to_csv('data/corr_table.csv')
table.corr().round(3).to_csv('data/corr_table_drops.csv')

Examin if there is a correlation between the above measures and if a patent experiences multiple binary pairs

In [29]:
# If the binary count is larger than 1, then the patent is marked as having multiple binary novelty
master['multiple novelty main: D-D'] = np.where(master['novelty count binary main: D-D'] > 1,1,0)
master['multiple novelty main: D-U'] = np.where(master['novelty count binary main: D-U'] > 1,1,0)
master['multiple novelty sub: D-D'] = np.where(master['novelty count binary sub: D-D'] > 1,1,0)
master['multiple novelty sub: D-U'] = np.where(master['novelty count binary sub: D-U'] > 1,1,0)

In [30]:
#Creating the measures table at the industry level that includes multiple binary
columns = master[['is novel binary main: D-D',\
                 'multiple novelty main: D-D',\
                 'is novel binary sub: D-D',\
                 'multiple novelty sub: D-D',\
                 'is novel binary main: D-U',\
                 'multiple novelty main: D-U',\
                 'is novel binary sub: D-U',\
                 'multiple novelty sub: D-U',\
                 'max novelty main: D-D',\
                 'max novelty sub: D-D',\
                 'max novelty main: D-U',\
                 'max novelty sub: D-U', \
                 'mainclass_id']]
table = columns.groupby('mainclass_id').mean().round(3).reset_index()
table['class name'] = table['mainclass_id'].map(design_class_dictionary.class_labels)
table

,mainclass_id,is novel binary main: D-D,multiple novelty main: D-D,is novel binary sub: D-D,multiple novelty sub: D-D,is novel binary main: D-U,multiple novelty main: D-U,is novel binary sub: D-U,multiple novelty sub: D-U,max novelty main: D-D,max novelty sub: D-D,max novelty main: D-U,max novelty sub: D-U,class name
0,D01,0.010,0.001,0.655,0.414,0.840,0.455,0.840,0.455,1.187,-3.179,-4.865,-4.865,Edible Products
1,D02,0.007,0.000,0.309,0.158,0.597,0.262,0.597,0.262,0.821,-2.647,-4.463,-4.463,Apparel and Haberdashery
2,D03,0.006,0.001,0.497,0.283,0.786,0.425,0.786,0.425,1.440,-2.494,-3.939,-3.939,"Travel Goods, Personal Belongings, and Storage..."
3,D04,0.011,0.001,0.345,0.157,0.681,0.371,0.681,0.371,0.488,-3.559,-4.330,-4.330,Brushware
4,D05,0.018,0.001,0.530,0.316,0.822,0.475,0.822,0.475,0.968,-3.240,-3.933,-3.933,Textile or Paper Yard Goods; Sheet Material
5,D06,0.008,0.001,0.414,0.229,0.751,0.301,0.751,0.301,1.304,-3.093,-4.779,-4.779,Furnishings
6,D07,0.005,0.001,0.453,0.253,0.714,0.340,0.714,0.340,1.207,-2.637,-4.236,-4.236,Equipment for Preparing or Serving Food or Dri...
7,D08,0.004,0.000,0.357,0.155,0.718,0.439,0.718,0.439,1.287,-3.181,-4.576,-4.576,Tools and Hardware
8,D09,0.006,0.001,0.517,0.330,0.776,0.395,0.776,0.395,1.020,-0.804,-3.090,-3.090,Packages and Containers for Goods
9,D10,0.007,0.001,0.339,0.151,0.745,0.332,0.745,0.332,1.328,-3.152,-5.308,-5.308,"Measuring, Testing or Signaling Instruments"
10,D11,0.008,0.001,0.507,0.276,0.711,0.286,0.711,0.286,1.295,-3.333,-5.383,-5.383,"Jewelry, Symbolic Insignia, and Ornaments"
11,D12,0.005,0.000,0.299,0.097,0.692,0.208,0.692,0.208,1.211,-4.795,-5.857,-5.857,Transportation
12,D13,0.002,0.000,0.283,0.104,0.640,0.364,0.640,0.364,0.959,-2.878,-4.285,-4.285,"Equipment for Production, Distribution, or Tra..."
13,D14,0.004,0.000,0.317,0.170,0.623,0.258,0.623,0.258,0.690,-2.280,-3.817,-3.817,"Recording, Communication, or Information Retri..."
14,D15,0.007,0.000,0.330,0.115,0.762,0.434,0.762,0.434,1.003,-4.565,-5.378,-5.378,Machines Not Elsewhere Specified
15,D16,0.007,0.000,0.272,0.129,0.540,0.292,0.540,0.292,1.108,-3.615,-4.991,-4.991,Photography and Optical Equipment
16,D17,0.033,0.002,0.314,0.133,0.545,0.310,0.545,0.310,1.100,-5.068,-6.313,-6.313,Musical Instruments
17,D18,0.010,0.000,0.304,0.136,0.607,0.256,0.607,0.256,0.960,-3.736,-5.649,-5.649,Printing and Office Machinery
18,D19,0.010,0.002,0.563,0.383,0.789,0.439,0.789,0.439,1.453,-1.947,-4.292,-4.292,Office Supplies; Artists' and Teachers' Materials
19,D20,0.005,0.001,0.528,0.294,0.848,0.511,0.848,0.511,1.493,-2.899,-4.346,-4.346,Sales and Advertising Equipment
20,D21,0.006,0.001,0.480,0.224,0.695,0.385,0.695,0.385,1.347,-4.839,-5.655,-5.655,"Games, Toys and Sports Goods"
21,D22,0.008,0.000,0.314,0.081,0.573,0.301,0.573,0.301,1.058,-5.124,-5.960,-5.960,"Arms, Pyrotechnics, Hunting and Fishing Equipment"
22,D23,0.007,0.001,0.291,0.119,0.755,0.308,0.755,0.308,1.061,-4.051,-5.046,-5.046,"Environmental Heating and Cooling, Fluid Handl..."
23,D24,0.013,0.002,0.380,0.161,0.675,0.435,0.675,0.435,1.270,-3.286,-4.439,-4.439,Medical and Laboratory Equipment
24,D25,0.008,0.000,0.356,0.113,0.743,0.465,0.743,0.465,1.264,-4.804,-5.022,-5.022,Building Units and Construction Elements
25,D26,0.002,0.000,0.349,0.131,0.732,0.224,0.732,0.224,1.065,-3.192,-4.045,-4.045,Lighting
26,D27,0.014,0.001,0.562,0.280,0.785,0.321,0.785,0.321,1.271,-4.441,-5.950,-5.950,Tobacco and Smokers' Supplies
27,D28,0.009,0.001,0.416,0.205,0.653,0.312,0.653,0.312,1.222,-3.865,-5.450,-5.450,Cosmetic Products and Toilet Articles
28,D29,0.011,0.001,0.393,0.161,0.668,0.404,0.668,0.404,0.529,-4.666,-4.922,-4.922,"Equipment for Safety, Protection and Rescue"
29,D30,0.005,0.001,0.576,0.319,0.710,0.499,0.710,0.499,1.366,-2.955,-4.888,-4.888,Animal Husbandry
30,D32,0.005,0.000,0.338,0.146,0.675,0.355,0.675,0.355,1.153,-4.231,-4.921,-4.921,"Washing, Cleaning or Drying Machines"
31,D34,0.006,0.001,0.369,0.164,0.731,0.470,0.731,0.470,1.252,-3.421,-4.374,-4.374,Material or Article Handling Equipment
32,D99,0.013,0.003,0.591,0.342,0.746,0.410,0.746,0.410,1.286,-3.520,-5.404,-5.404,Miscellaneous

In [31]:
#save this table
# table.to_csv('data/table.csv')
table.to_csv('data/table_drops.csv')

In [47]:
#count the number of occurances in each mainclass
columns

,is novel binary main: D-D,multiple novelty main: D-D,is novel binary sub: D-D,multiple novelty sub: D-D,is novel binary main: D-U,multiple novelty main: D-U,is novel binary sub: D-U,multiple novelty sub: D-U,max novelty main: D-D,max novelty sub: D-D,max novelty main: D-U,max novelty sub: D-U,mainclass_id
0,NaN,0,NaN,0,1.0,1,1.0,1,NaN,NaN,-4.951017,-4.951017,D19
1,NaN,0,NaN,0,1.0,1,1.0,1,NaN,NaN,-5.724207,-5.724207,D06
2,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D23
3,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D23
4,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D23
5,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D23
6,NaN,0,NaN,0,1.0,1,1.0,1,NaN,NaN,-2.018799,-2.018799,D25
7,1.0,1,1.0,1,NaN,0,NaN,0,-0.167627,-2.440246,NaN,NaN,D25
8,1.0,1,1.0,1,NaN,0,NaN,0,0.015794,-3.117429,NaN,NaN,D09
9,1.0,1,1.0,1,NaN,0,NaN,0,0.015794,-3.117429,NaN,NaN,D09
10,1.0,1,1.0,1,NaN,0,NaN,0,0.015794,-2.772589,NaN,NaN,D09
11,1.0,1,1.0,1,NaN,0,NaN,0,0.015794,-3.117429,NaN,NaN,D09
12,1.0,1,1.0,1,NaN,0,NaN,0,0.015794,-3.117429,NaN,NaN,D09
13,NaN,0,NaN,0,1.0,1,1.0,1,NaN,NaN,-2.355271,-2.355271,D25
14,1.0,1,1.0,1,NaN,0,NaN,0,0.015794,-3.117429,NaN,NaN,D09
15,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D23
16,1.0,0,1.0,0,1.0,0,1.0,0,1.662972,-7.060305,-7.852439,-7.852439,D24
17,1.0,1,1.0,1,1.0,1,1.0,1,0.759420,-1.747099,-3.575773,-3.575773,D24
18,1.0,1,1.0,1,NaN,0,NaN,0,0.960730,-5.114395,NaN,NaN,D06
19,1.0,1,1.0,1,NaN,0,NaN,0,0.015794,-2.212973,NaN,NaN,D09
20,1.0,1,1.0,1,NaN,0,NaN,0,0.015794,-2.772589,NaN,NaN,D09
21,1.0,1,1.0,1,NaN,0,NaN,0,0.015794,-2.772589,NaN,NaN,D09
22,1.0,1,1.0,1,NaN,0,NaN,0,0.015794,-3.117429,NaN,NaN,D09
23,1.0,1,1.0,1,NaN,0,NaN,0,0.015794,-3.117429,NaN,NaN,D09
24,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D23
25,NaN,0,NaN,0,1.0,1,1.0,1,NaN,NaN,-2.355271,-2.355271,D25
26,1.0,0,1.0,0,NaN,0,NaN,0,0.998470,-6.723832,NaN,NaN,D06
27,1.0,0,1.0,1,NaN,0,NaN,0,1.201417,-4.450235,NaN,NaN,D09
28,NaN,0,NaN,0,1.0,0,1.0,0,NaN,NaN,-5.935516,-5.935516,D11
29,NaN,0,NaN,0,1.0,0,1.0,0,NaN,NaN,-6.417355,-6.417355,D12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
481156,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D14
481157,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D14
481158,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D23
481159,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D30
481160,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D03
481161,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D03
481162,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D07
481163,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D08
481164,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D09
481165,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D09
481166,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D09
481167,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D09
481168,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D11
481169,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D21
481170,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D23
481171,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D23
481172,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D28
481173,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D06
481174,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D07
481175,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D07
481176,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D07
481177,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D09
481178,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D09
481179,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D09
481180,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D09
481181,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D13
481182,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D14
481183,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D16
481184,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D21
481185,NaN,0,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,D23

In [32]:
#correlation
table.corr().round(3)

,is novel binary main: D-D,multiple novelty main: D-D,is novel binary sub: D-D,multiple novelty sub: D-D,is novel binary main: D-U,multiple novelty main: D-U,is novel binary sub: D-U,multiple novelty sub: D-U,max novelty main: D-D,max novelty sub: D-D,max novelty main: D-U,max novelty sub: D-U
is novel binary main: D-D,1.000,0.546,0.111,0.106,-0.167,0.048,-0.167,0.048,-0.090,-0.334,-0.395,-0.395
multiple novelty main: D-D,0.546,1.000,0.580,0.581,0.292,0.356,0.292,0.356,0.308,0.140,-0.047,-0.047
is novel binary sub: D-D,0.111,0.580,1.000,0.958,0.686,0.540,0.686,0.540,0.450,0.339,0.159,0.159
multiple novelty sub: D-D,0.106,0.581,0.958,1.000,0.642,0.478,0.642,0.478,0.392,0.527,0.297,0.297
is novel binary main: D-U,-0.167,0.292,0.686,0.642,1.000,0.566,1.000,0.566,0.423,0.322,0.347,0.347
multiple novelty main: D-U,0.048,0.356,0.540,0.478,0.566,1.000,0.566,1.000,0.305,0.169,0.306,0.306
is novel binary sub: D-U,-0.167,0.292,0.686,0.642,1.000,0.566,1.000,0.566,0.423,0.322,0.347,0.347
multiple novelty sub: D-U,0.048,0.356,0.540,0.478,0.566,1.000,0.566,1.000,0.305,0.169,0.306,0.306
max novelty main: D-D,-0.090,0.308,0.450,0.392,0.423,0.305,0.423,0.305,1.000,0.080,-0.162,-0.162
max novelty sub: D-D,-0.334,0.140,0.339,0.527,0.322,0.169,0.322,0.169,0.080,1.000,0.825,0.825
max novelty main: D-U,-0.395,-0.047,0.159,0.297,0.347,0.306,0.347,0.306,-0.162,0.825,1.000,1.000
max novelty sub: D-U,-0.395,-0.047,0.159,0.297,0.347,0.306,0.347,0.306,-0.162,0.825,1.000,1.000

In [33]:
#Save the correlation table
# table.corr().round(3).to_csv('data/corr_table.csv')
table.corr().round(3).to_csv('data/corr_table_drops.csv')

Below are a bit of descriptive stats for the above measures

In [34]:
master['is novel binary main: D-D'].value_counts()

0.0    179515
1.0      1171
Name: is novel binary main: D-D, dtype: int64

In [35]:
master['is novel binary sub: D-D'].value_counts()

0.0    219754
1.0    137035
Name: is novel binary sub: D-D, dtype: int64

In [36]:
master['is novel binary main: D-U'].value_counts()

1.0    185356
0.0     79819
Name: is novel binary main: D-U, dtype: int64

In [37]:
master['is novel binary sub: D-U'].value_counts()

1.0    185356
0.0     79819
Name: is novel binary sub: D-U, dtype: int64

In [38]:
master['max novelty main: D-D'].describe()

count    180686.000000
mean          1.131138
std           0.862992
min          -2.419116
25%           0.576531
50%           1.163415
75%           1.686958
max           5.122075
Name: max novelty main: D-D, dtype: float64

In [39]:
master['max novelty sub: D-D'].describe()

count    356789.000000
mean         -3.153037
std           2.056182
min         -12.319531
25%          -4.522009
50%          -3.059785
75%          -1.684921
max           4.066306
Name: max novelty sub: D-D, dtype: float64

In [40]:
master['max novelty main: D-U'].describe()

count    265175.000000
mean         -4.641554
std           1.808427
min         -12.938082
25%          -5.789913
50%          -4.546183
75%          -3.370744
max           2.068477
Name: max novelty main: D-U, dtype: float64

In [41]:
master['max novelty sub: D-U'].describe()

count    265175.000000
mean         -4.641554
std           1.808427
min         -12.938082
25%          -5.789913
50%          -4.546183
75%          -3.370744
max           2.068477
Name: max novelty sub: D-U, dtype: float64